# Generated by Django 5.2.4 on 2026-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
    ]
